# Add your OpenAI API key here when deploying to Streamlit Cloud
# OPENAI_API_KEY = "your-api-key-here"

# This file is for reference only - actual secrets should be added
# through the Streamlit Cloud dashboard interface 